export const BOOK_TICKET_START = 'BOOK_TICKET_START';
export const BOOK_TICKET_SUCCESS = 'BOOK_TICKET_SUCCESS';
export const BOOK_TICKET_FAILURE = 'BOOK_TICKET_FAILURE';
export const CLEAR_BOOKING_ERRORS = 'CLEAR_BOOKING_ERRORS';
