export const PLAY_NOT_EXIST = 'PLAY_NOT_EXIST';
export const PLAY_NOT_ENOUGH_SEATS = 'PLAY_NOT_ENOUGH_SEATS';
export const PLAY_IS_BOOKED = 'PLAY_IS_BOOKED';

export const BAD_REQUEST = 'BAD_REQUEST';
export const VALIDATION_ERROR = 'VALIDATION_ERROR';
